### ISSUE TITLE
How to remove this?

### ISSUE THREAD

**Issue by EvilQoo** [staticdev/staticdev#4]
This is for the [pdf-split-tool](https://github.com/staticdev/pdf-split-tool)

"has more than 200kb per page. Consider reducing resolution before splitting.
Do you want to continue? [y/N]"

can help to remove this vaildate?

Thanks.

**Comment by staticdev** [comment]
@EvilQoo this feature does not exist, but you can change this line https://github.com/staticdev/pdf-split-tool/blob/master/src/pdf_split_tool/__main__.py#L18 to:

`valid = True`

**Comment by EvilQoo** [comment]
Thanks for the reply.

I changed , but still having the same issue. Do I need to do anything to
take effect of the changes?
valid = True
[image: Image 001.png]

**Comment by staticdev** [comment]
@EvilQoo sorry I don't see your image.. it should be ok if you just change that. After you change the code you can do:

```
poetry install
poetry run + command you want to split
```

**Comment by EvilQoo** [comment]
I've changed to valid = True , but it still prompt ask Yes or No. Please
help to test. Appreciated your help.

Thanks.

**Comment by staticdev** [comment]
I tested here and it worked, try to uninstall it if you have installed.

**Comment by EvilQoo** [comment]
Uninstall python? Or the pdf-spilt-tool?

**Comment by staticdev** [comment]
Uninstall pdf-spilt-tool if you have it installed somehow.

**Comment by EvilQoo** [comment]
I uninstall pdf-spilt-tool and reinstall python too.
Without the pdf-spilt-tool pip I'm able to run that pdf-spilt-tool command
but the validation is still there.
is there anything i missed out here?

**Comment by EvilQoo** [comment]
I managed to remove that validation.

Is there a way to support subfolder?
Thanks.

**Comment by staticdev** [comment]
@EvilQoo I am sorry but I will not work on this project anymore. It is archived.

**Comment by EvilQoo** [comment]
Ok, thanks for the reply. Wish you can help on this last part.

**Comment by staticdev** [comment]
@EvilQoo sorry for the delay, long vacation. Even with the project archived it is possible to clone and modify it. Feel free to change anything you want.
