### ISSUE TITLE
Interested in improving django-pagination-bootstrap

### ISSUE THREAD

**Issue by urtzai** [staticdev/staticdev#5]
Hi, 

I am a Django developer in a company called [CodeSyntax](https://www.codesyntax.com/en) and we are interested in the maintenance of [django-pagination-bootstrap](https://github.com/staticdev/django-pagination-bootstrap).

I already have some minor changes to apply on templates for Django 4.1 compatibility. What can we do?

Urtzi

**Comment by staticdev** [comment]
Yes, sure.. I am not sure exactly what do I have to change though. Do you have suggestions on how we proceed?

**Comment by urtzai** [comment]
You can just create a team and give me some permissions, or transfer an entire project. Both are available from project's general settings:

1) Settings -> Collaborators and teams
2) Settings -> General -> Danger Zone -> Transfer ownership

If your choice is to transfer the entire project, please, consider transferring to our organization called [codesyntax](https://github.com/codesyntax/).

Thanks!

**Comment by staticdev** [comment]
@urtzai I unarchived the project and added you as Collaborator to start with. I can also put other people from codesyntax, since I didn't see a way to add an organization as Collaborator.

**Comment by staticdev** [comment]
@urtzai i also released a security update version 2.4.5, when I unarchived i received tons of security alerts about dependencies. Now it is on you.

**Comment by staticdev** [comment]
We can continue like this for now, if you want to change something you can let me know in another issue.
