### ISSUE TITLE
Are you still maintaining PyInquirer?

### ISSUE THREAD

**Issue by Ralithune** [staticdev/staticdev#6]
I saw a note about you taking over the maintenance of PyInquirer from a couple years back - I was hoping we could get some eyes on a crash that happens when the terminal is clicked on. https://github.com/CITGuru/PyInquirer/issues/178

**Comment by staticdev** [comment]
Sorry @Ralithune.. I stepped out as maintainer from 6 of February of this year since I am overloaded with other projects. I would recommend you create an issue there since they current maintainers may be able to help you. Hope this helps.
